# Generated by Django 4.0.6 on 2023-01-24 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0014_alter_bibfiles_insertdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reverseindexitem',
            old_name='literature',
            new_name='literature_id',
        ),
        migrations.AlterField(
            model_name='bibfiles',
            name='insertDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 20, 56, 4, 555368)),
        ),
    ]
