# Generated by Django 4.0.6 on 2023-03-16 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_rename_literature_reverseindexitem_literature_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibfiles',
            name='insertDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 16, 22, 56, 53, 121420)),
        ),
    ]
