# Generated by Django 4.0.6 on 2023-03-16 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0016_alter_bibfiles_insertdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reverseindexitem',
            old_name='literature_id',
            new_name='literature',
        ),
        migrations.AlterField(
            model_name='bibfiles',
            name='insertDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 16, 23, 43, 29, 603378)),
        ),
    ]
