# Generated by Django 4.0.6 on 2023-03-17 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0017_rename_literature_id_reverseindexitem_literature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibfiles',
            name='insertDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 17, 11, 54, 1, 20695)),
        ),
    ]
